#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}==============================================${NC}"
echo -e "${GREEN}🎮 GCP Minecraft On-Demand - Interactive Setup${NC}"
echo -e "${GREEN}==============================================${NC}"
echo "This script will help you configure your local environment"
echo "and generate your terraform variables to deploy the project."
echo ""

# 1. Dependency Checks
echo -e "${YELLOW}[1/4] Checking Dependencies...${NC}"
if ! command -v gcloud &> /dev/null; then
    echo -e "${RED}Error: 'gcloud' CLI is not installed. Please install it first.${NC}"
    echo "Visit: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: 'terraform' is not installed. Please install it first.${NC}"
    echo "Visit: https://developer.hashicorp.com/terraform/install"
    exit 1
fi
echo "✅ Dependencies found."
echo ""

# 2. GCP Authentication Check
echo -e "${YELLOW}[2/4] Checking GCP Authentication...${NC}"
if ! gcloud auth application-default print-access-token &> /dev/null; then
    echo "You need to authenticate with Google Cloud first."
    gcloud auth application-default login
else
    echo "✅ Already authenticated with GCP."
fi
echo ""

# 3. Variable Configuration
echo -e "${YELLOW}[3/4] Configuring Terraform Variables...${NC}"

TFVARS_FILE="terraform/terraform.tfvars"
if [ -f "$TFVARS_FILE" ]; then
    echo -e "${YELLOW}Notice: $TFVARS_FILE already exists.${NC}"
    read -p "Do you want to overwrite it? (y/N): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        SKIP_CONFIG=true
    else
        SKIP_CONFIG=false
    fi
else
    SKIP_CONFIG=false
fi

if [ "$SKIP_CONFIG" = false ]; then
    read -p "Enter your GCP Project ID (e.g., my-project-123): " PROJECT_ID
    read -p "Enter your Minecraft Domain (e.g., mc.yourdomain.com): " DOMAIN_NAME
    
    # Suggest a DNS Zone name based on domain
    SUGGESTED_ZONE=$(echo "$DOMAIN_NAME" | tr '.' '-')
    read -p "Enter a name for the Cloud DNS Zone [$SUGGESTED_ZONE]: " DNS_ZONE_NAME
    DNS_ZONE_NAME=${DNS_ZONE_NAME:-$SUGGESTED_ZONE}

    read -s -p "Enter a secure Admin Passcode for the web portal: " ADMIN_PASSCODE
    echo ""
    read -p "Enter your Discord Webhook URL for whitelist requests: " DISCORD_WEBHOOK_URL

    echo ""
    echo "Which DNS Provider are you using for dynamic updates?"
    echo "1) Google Cloud DNS (Default, recommended if you delegate from Cloudflare)"
    echo "2) Cloudflare"
    echo "3) DuckDNS"
    echo "4) Dynu"
    echo "5) None"
    read -p "Select [1-5]: " DNS_CHOICE

    case $DNS_CHOICE in
        2)
            DNS_PROVIDER="cloudflare"
            read -p "Enter your Cloudflare API Token: " DNS_API_TOKEN
            read -p "Enter your Cloudflare Zone ID: " CLOUDFLARE_ZONE_ID
            ;;
        3)
            DNS_PROVIDER="duckdns"
            read -p "Enter your DuckDNS Token: " DNS_API_TOKEN
            CLOUDFLARE_ZONE_ID=""
            ;;
        4)
            DNS_PROVIDER="dynu"
            read -p "Enter your Dynu API Token/Password: " DNS_API_TOKEN
            CLOUDFLARE_ZONE_ID=""
            ;;
        5)
            DNS_PROVIDER="none"
            DNS_API_TOKEN=""
            CLOUDFLARE_ZONE_ID=""
            ;;
        *)
            DNS_PROVIDER="google"
            DNS_API_TOKEN=""
            CLOUDFLARE_ZONE_ID=""
            ;;
    esac

    # Write to terraform.tfvars
    cat > "$TFVARS_FILE" <<EOF
# Auto-generated by setup.sh
project_id          = "$PROJECT_ID"
domain_name         = "$DOMAIN_NAME"
dns_zone_name       = "$DNS_ZONE_NAME"
admin_passcode      = "$ADMIN_PASSCODE"
discord_webhook_url = "$DISCORD_WEBHOOK_URL"
dns_provider        = "$DNS_PROVIDER"
EOF

    if [ -n "$DNS_API_TOKEN" ]; then
        echo "dns_api_token       = \"$DNS_API_TOKEN\"" >> "$TFVARS_FILE"
    fi
    if [ -n "$CLOUDFLARE_ZONE_ID" ]; then
        echo "cloudflare_zone_id  = \"$CLOUDFLARE_ZONE_ID\"" >> "$TFVARS_FILE"
    fi

    echo "✅ Configuration saved to $TFVARS_FILE."
else
    # Extract project ID from existing file for the API step
    PROJECT_ID=$(grep -E '^project_id\s*=' "$TFVARS_FILE" | awk -F'"' '{print $2}')
fi
echo ""

# 4. Enabling APIs
if [ -n "$PROJECT_ID" ]; then
    echo -e "${YELLOW}[4/4] Enabling Required GCP APIs for project: $PROJECT_ID...${NC}"
    echo "This may take a few minutes..."
    gcloud services enable \
      compute.googleapis.com \
      dns.googleapis.com \
      pubsub.googleapis.com \
      logging.googleapis.com \
      cloudfunctions.googleapis.com \
      cloudbuild.googleapis.com \
      artifactregistry.googleapis.com \
      secretmanager.googleapis.com \
      --project="$PROJECT_ID"
    echo "✅ APIs enabled successfully."
else
    echo -e "${YELLOW}[4/4] Skipping API enablement (Project ID not found).${NC}"
fi

echo ""
echo -e "${GREEN}==============================================${NC}"
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo -e "${GREEN}==============================================${NC}"
echo "You are now ready to deploy the infrastructure."
echo ""
echo "Next Steps:"
echo "1. Verify your configuration in: terraform/terraform.tfvars"
echo "2. Run the following commands:"
echo -e "${YELLOW}   cd terraform${NC}"
echo -e "${YELLOW}   terraform init${NC}"
echo -e "${YELLOW}   terraform apply${NC}"
echo ""
