# Requires -Version 3.0
$ErrorActionPreference = "Stop"

function Write-ColorHost {
    param([string]$Text, [string]$Color)
    Write-Host $Text -ForegroundColor $Color
}

Write-ColorHost "==============================================" "Green"
Write-ColorHost "🎮 GCP Minecraft On-Demand - Interactive Setup" "Green"
Write-ColorHost "==============================================" "Green"
Write-Host "This script will help you configure your local environment"
Write-Host "and generate your terraform variables to deploy the project."
Write-Host ""

# 1. Dependency Checks
Write-ColorHost "[1/4] Checking Dependencies..." "Yellow"
if (-not (Get-Command "gcloud" -ErrorAction SilentlyContinue)) {
    Write-ColorHost "Error: 'gcloud' CLI is not installed. Please install it first." "Red"
    Write-Host "Visit: https://cloud.google.com/sdk/docs/install"
    exit 1
}

if (-not (Get-Command "terraform" -ErrorAction SilentlyContinue)) {
    Write-ColorHost "Error: 'terraform' is not installed. Please install it first." "Red"
    Write-Host "Visit: https://developer.hashicorp.com/terraform/install"
    exit 1
}
Write-Host "✅ Dependencies found."
Write-Host ""

# 2. GCP Authentication Check
Write-ColorHost "[2/4] Checking GCP Authentication..." "Yellow"
try {
    $null = gcloud auth application-default print-access-token 2>$null
    Write-Host "✅ Already authenticated with GCP."
} catch {
    Write-Host "You need to authenticate with Google Cloud first."
    gcloud auth application-default login
}
Write-Host ""

# 3. Variable Configuration
Write-ColorHost "[3/4] Configuring Terraform Variables..." "Yellow"

# Assuming script is run from the root directory or inside scripts/windows
$WorkspaceRoot = (Get-Item .).FullName
if ((Split-Path $WorkspaceRoot -Leaf) -eq "windows") {
    $WorkspaceRoot = (Get-Item ..\..).FullName
} elseif ((Split-Path $WorkspaceRoot -Leaf) -eq "scripts") {
    $WorkspaceRoot = (Get-Item ..).FullName
}

$TfvarsFile = Join-Path $WorkspaceRoot "terraform\terraform.tfvars"
$SkipConfig = $false

if (Test-Path $TfvarsFile) {
    Write-ColorHost "Notice: terraform\terraform.tfvars already exists." "Yellow"
    $Overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($Overwrite -notmatch "^[Yy]$") {
        Write-Host "Keeping existing configuration."
        $SkipConfig = $true
    }
}

if (-not $SkipConfig) {
    $ProjectID = Read-Host "Enter your GCP Project ID (e.g., my-project-123)"
    $DomainName = Read-Host "Enter your Minecraft Domain (e.g., mc.yourdomain.com)"
    
    $SuggestedZone = $DomainName -replace '\.', '-'
    $DnsZoneName = Read-Host "Enter a name for the Cloud DNS Zone [$SuggestedZone]"
    if ([string]::IsNullOrWhiteSpace($DnsZoneName)) {
        $DnsZoneName = $SuggestedZone
    }

    $AdminPasscode = Read-Host "Enter a secure Admin Passcode for the web portal (input will not be hidden)"
    $DiscordWebhook = Read-Host "Enter your Discord Webhook URL for whitelist requests"

    Write-Host ""
    Write-Host "Which DNS Provider are you using for dynamic updates?"
    Write-Host "1) Google Cloud DNS (Default, recommended if you delegate from Cloudflare)"
    Write-Host "2) Cloudflare"
    Write-Host "3) DuckDNS"
    Write-Host "4) Dynu"
    Write-Host "5) None"
    $DnsChoice = Read-Host "Select [1-5]"

    $DnsProvider = "google"
    $DnsApiToken = ""
    $CloudflareZoneId = ""

    switch ($DnsChoice) {
        "2" {
            $DnsProvider = "cloudflare"
            $DnsApiToken = Read-Host "Enter your Cloudflare API Token"
            $CloudflareZoneId = Read-Host "Enter your Cloudflare Zone ID"
        }
        "3" {
            $DnsProvider = "duckdns"
            $DnsApiToken = Read-Host "Enter your DuckDNS Token"
        }
        "4" {
            $DnsProvider = "dynu"
            $DnsApiToken = Read-Host "Enter your Dynu API Token/Password"
        }
        "5" {
            $DnsProvider = "none"
        }
    }

    $ConfigContent = @"
# Auto-generated by setup.ps1
project_id          = `"$ProjectID`"
domain_name         = `"$DomainName`"
dns_zone_name       = `"$DnsZoneName`"
admin_passcode      = `"$AdminPasscode`"
discord_webhook_url = `"$DiscordWebhook`"
dns_provider        = `"$DnsProvider`"
"@

    if (-not [string]::IsNullOrWhiteSpace($DnsApiToken)) {
        $ConfigContent += "`r`ndns_api_token       = `"$DnsApiToken`""
    }
    if (-not [string]::IsNullOrWhiteSpace($CloudflareZoneId)) {
        $ConfigContent += "`r`ncloudflare_zone_id  = `"$CloudflareZoneId`""
    }

    Set-Content -Path $TfvarsFile -Value $ConfigContent -Encoding UTF8
    Write-Host "✅ Configuration saved to terraform\terraform.tfvars."
} else {
    # Attempt to extract project_id from the existing tfvars file
    $ProjectLine = Select-String -Path $TfvarsFile -Pattern "^project_id\s*=\s*`"(.+)`""
    if ($ProjectLine) {
        $ProjectID = $ProjectLine.Matches.Groups[1].Value
    }
}
Write-Host ""

# 4. Enabling APIs
if (-not [string]::IsNullOrWhiteSpace($ProjectID)) {
    Write-ColorHost "[4/4] Enabling Required GCP APIs for project: $ProjectID..." "Yellow"
    Write-Host "This may take a few minutes..."
    gcloud services enable compute.googleapis.com dns.googleapis.com pubsub.googleapis.com logging.googleapis.com cloudfunctions.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com --project="$ProjectID"
    Write-Host "✅ APIs enabled successfully."
} else {
    Write-ColorHost "[4/4] Skipping API enablement (Project ID not found)." "Yellow"
}

Write-Host ""
Write-ColorHost "==============================================" "Green"
Write-ColorHost "🎉 Setup Complete!" "Green"
Write-ColorHost "==============================================" "Green"
Write-Host "You are now ready to deploy the infrastructure."
Write-Host ""
Write-Host "Next Steps:"
Write-Host "1. Verify your configuration in: terraform\terraform.tfvars"
Write-Host "2. Run the following commands:"
Write-ColorHost "   cd terraform" "Yellow"
Write-ColorHost "   terraform init" "Yellow"
Write-ColorHost "   terraform apply" "Yellow"
Write-Host ""
